### ISSUE TITLE
Feature Request: Record & report usage statistics for (pre-)quantification steps

### ISSUE THREAD

**Issue by rob-p** [lweasel/piquant#50]
I'm *really* liking piquant!  It's making the synthetic benchmarking for our new manuscript so much easier than would otherwise be the case.  The wealth of statistics and plots it produces already allow me to explore almost all of the variables of interest I care about.  However, one feature that would be *incredibly* useful is the ability to record / report the resource usage of the quantification and pre-quantification steps.  For example, recording the memory usage and runtime required by each tool and providing some sort of simple visualization of this would be very slick.  

Obviously, since I'm focusing on methods that are AFAP (as fast as possible --- subject to being highly-accurate), this is a somewhat selfish feature request ;P.  However, I do think it would be generally useful to have, as it also lets us explore how e.g. the memory and time resources required by a method vary with the size of the input dataset.

**Comment by lweasel** [comment]
Hopefully not treading on toes, but I had a few spare hours so I've had a stab at adding a couple of graphs for the prequantification resource usage data. The "resource_usage_graphs" directory should now contain two extra graphs at the top level - "prequant_time_usage.pdf" is a bar plot comparing the real, user and kernel mode time taken by prequantification for each quantification method, and prequant_memory_usage.pdf is a bar plot comparing the maximum resident memory.

**Comment by rob-p** [comment]
Awesome!  No toe-stepping at all (I've been busy with other things in Salmon).  This feature sounds great; I'll try it out immediately.
